import type { Course, Module, Achievement } from '@/types';

export const SEED_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_code',
    name: 'Birinchi qadam',
    description: 'Birinchi bor kod yozib, uni muvaffaqiyatli ishga tushirdingiz!',
    icon: '🚀',
    category: 'coding',
    requirement: 'Birinchi dasturni ishga tushirish',
    xpReward: 50,
  },
  {
    id: 'first_lesson',
    name: 'Ilk g‘alaba',
    description: 'Birinchi darsni to‘liq o‘zlashtirib, testdan o‘tdingiz.',
    icon: '🎯',
    category: 'learning',
    requirement: '1 ta darsni to‘liq yakunlash',
    xpReward: 100,
  },
  {
    id: 'bug_hunter',
    name: 'Xatolar ovchisi',
    description: 'Koddagi xatoni tahlil qilib, uni muvaffaqiyatli tuzatdingiz.',
    icon: '🐞',
    category: 'coding',
    requirement: '1 ta xatoni to‘g‘rilash',
    xpReward: 75,
  },
  {
    id: 'streak_3',
    name: 'Qat’iyatli talaba',
    description: '3 kun ketma-ket platformada kod yozdingiz.',
    icon: '🔥',
    category: 'streak',
    requirement: '3 kunlik uzluksiz o‘qish',
    xpReward: 150,
  },
  {
    id: 'quiz_master',
    name: 'Sinovlar ustasi',
    description: 'Quiz savollariga 100% to‘g‘ri javob berdingiz.',
    icon: '⭐',
    category: 'learning',
    requirement: 'Dars quizini 100% bajarish',
    xpReward: 80,
  },
  {
    id: 'html_creator',
    name: 'HTML me’mori',
    description: 'HTML asoslari kursining barcha amaliy topshiriqlarini yakunladingiz.',
    icon: '🌐',
    category: 'project',
    requirement: 'HTML kursini yakunlash',
    xpReward: 300,
  },
  {
    id: 'css_designer',
    name: 'CSS sehrgari',
    description: 'Web sahifalarga go‘zal uslub berishni to‘liq o‘zlashtirdingiz.',
    icon: '🎨',
    category: 'project',
    requirement: 'CSS kursini yakunlash',
    xpReward: 300,
  },
  {
    id: 'js_ninja',
    name: 'JavaScript ninja',
    description: 'Interaktiv veb dasturlash asoslarini egalladingiz.',
    icon: '⚡',
    category: 'coding',
    requirement: 'JS kursini yakunlash',
    xpReward: 400,
  },
  {
    id: 'pure_coder',
    name: 'Haqiqiy dasturchi',
    description: 'Nusxa ko‘chirmasdan (paste qilmasdan) kodni klaviaturada to‘liq o‘zingiz yozdingiz.',
    icon: '⌨️',
    category: 'coding',
    requirement: 'Paste qilmasdan mashqni bajarish',
    xpReward: 100,
  },
  {
    id: 'level_up_5',
    name: '5-daraja dasturchi',
    description: 'O‘quv jarayonida 5-darajaga yetib keldingiz!',
    icon: '👑',
    category: 'learning',
    requirement: '5-darajaga yetish',
    xpReward: 250,
  },
];

// ==========================================
// COURSES
// ==========================================
export const SEED_COURSES: Course[] = [
  {
    id: 'course-intro',
    title: 'Dasturlashga Kirish',
    slug: 'dasturlashga-kirish',
    description: 'Dasturlash nima, kompyuter qanday fikrlaydi va dasturchi kabi fikrlash asoslarini 0 dan o‘rganing.',
    shortDescription: '0 dan boshlovchilar uchun: fikrlash, algoritmlar va ilk kod.',
    level: 'boshlangich',
    category: 'kirish',
    thumbnail: '/images/courses/intro.svg',
    estimatedHours: 4,
    published: true,
    order: 1,
    technologies: ['Algoritm', 'Mantiq', 'Terminal', 'Console'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-html',
    title: 'HTML Asoslari',
    slug: 'html-asoslari',
    description: 'Internetdagi barcha veb-saytlarning skeleti bo‘lgan HTML tilini to‘liq o‘rganing va shaxsiy sahifangizni yarating.',
    shortDescription: 'Veb sahifalarning suyagi va teglari bilan ishlash.',
    level: 'boshlangich',
    category: 'frontend',
    thumbnail: '/images/courses/html.svg',
    estimatedHours: 6,
    published: true,
    order: 2,
    technologies: ['HTML5', 'Semantic Tags', 'Forms', 'Media'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-css',
    title: 'CSS Asoslari',
    slug: 'css-asoslari',
    description: 'Sahifalarga rang, chiroyli shakl va zamonaviy ko‘rinish berish: Flexbox, Grid va responsive dizayn.',
    shortDescription: 'Saytlarni chiroyli, zamonaviy va har qanday ekranga mos qilish.',
    level: 'boshlangich',
    category: 'frontend',
    thumbnail: '/images/courses/css.svg',
    estimatedHours: 8,
    published: true,
    order: 3,
    technologies: ['CSS3', 'Flexbox', 'Grid', 'Media Queries'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-js',
    title: 'JavaScript Asoslari',
    slug: 'javascript-asoslari',
    description: 'Saytlarga jon kiritish! O‘zgaruvchilar, funksiyalar, shartlar va tugmalarni bosganda ishlaydigan interaktivlik.',
    shortDescription: 'Vebning eng mashhur dasturlash tili: mantiq va harakat.',
    level: 'boshlangich',
    category: 'frontend',
    thumbnail: '/images/courses/js.svg',
    estimatedHours: 10,
    published: true,
    order: 4,
    technologies: ['JavaScript ES6', 'DOM', 'Events', 'Functions'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_MODULES: Module[] = [
  // Intro modules
  {
    id: 'mod-intro-1',
    courseId: 'course-intro',
    title: '1-Modul: Dasturlash Falsafasi va Algoritm',
    description: 'Dasturchi kabi fikrlashni o‘rganamiz.',
    order: 1,
  },
  // HTML modules
  {
    id: 'mod-html-1',
    courseId: 'course-html',
    title: '1-Modul: Vebning Skeleti (HTML)',
    description: 'Teglar, matnlar va sahifa tuzilishi.',
    order: 1,
  },
  // CSS modules
  {
    id: 'mod-css-1',
    courseId: 'course-css',
    title: '1-Modul: Ranglar, Qutilar va Tartib',
    description: 'CSS selektorlari, Box model va tartiblash.',
    order: 1,
  },
  // JS modules
  {
    id: 'mod-js-1',
    courseId: 'course-js',
    title: '1-Modul: Jonli Veb (JavaScript)',
    description: 'O‘zgaruvchilar, funksiyalar va DOM boshqaruvi.',
    order: 1,
  },
];
