import type { Course, Module, Achievement } from '@/types';

export const SEED_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_code',
    name: 'Birinchi qadam',
    description: 'Birinchi bor kod yozib, uni muvaffaqiyatli ishga tushirdingiz!',
    icon: '🚀',
    category: 'coding',
    requirement: 'Birinchi dasturni ishga tushirish',
    xpReward: 50,
  },
  {
    id: 'first_lesson',
    name: 'Ilk g‘alaba',
    description: 'Birinchi darsni to‘liq o‘zlashtirib, testdan o‘tdingiz.',
    icon: '🎯',
    category: 'learning',
    requirement: '1 ta darsni to‘liq yakunlash',
    xpReward: 100,
  },
  {
    id: 'bug_hunter',
    name: 'Xatolar ovchisi',
    description: 'Koddagi xatoni tahlil qilib, uni muvaffaqiyatli tuzatdingiz.',
    icon: '🐞',
    category: 'coding',
    requirement: '1 ta xatoni to‘g‘rilash',
    xpReward: 75,
  },
  {
    id: 'streak_3',
    name: 'Qat’iyatli talaba',
    description: '3 kun ketma-ket platformada kod yozdingiz.',
    icon: '🔥',
    category: 'streak',
    requirement: '3 kunlik uzluksiz o‘qish',
    xpReward: 150,
  },
  {
    id: 'quiz_master',
    name: 'Sinovlar ustasi',
    description: 'Quiz savollariga 100% to‘g‘ri javob berdingiz.',
    icon: '⭐',
    category: 'learning',
    requirement: 'Dars quizini 100% bajarish',
    xpReward: 80,
  },
  {
    id: 'html_creator',
    name: 'HTML me’mori',
    description: 'HTML asoslari kursining barcha amaliy topshiriqlarini yakunladingiz.',
    icon: '🌐',
    category: 'project',
    requirement: 'HTML kursini yakunlash',
    xpReward: 300,
  },
  {
    id: 'css_designer',
    name: 'CSS sehrgari',
    description: 'Web sahifalarga go‘zal uslub berishni to‘liq o‘zlashtirdingiz.',
    icon: '🎨',
    category: 'project',
    requirement: 'CSS kursini yakunlash',
    xpReward: 300,
  },
  {
    id: 'js_ninja',
    name: 'JavaScript ninja',
    description: 'Interaktiv veb dasturlash asoslarini egalladingiz.',
    icon: '⚡',
    category: 'coding',
    requirement: 'JS kursini yakunlash',
    xpReward: 400,
  },
  {
    id: 'pure_coder',
    name: 'Haqiqiy dasturchi',
    description: 'Nusxa ko‘chirmasdan (paste qilmasdan) kodni klaviaturada to‘liq o‘zingiz yozdingiz.',
    icon: '⌨️',
    category: 'coding',
    requirement: 'Paste qilmasdan mashqni bajarish',
    xpReward: 100,
  },
  {
    id: 'level_up_5',
    name: '5-daraja dasturchi',
    description: 'O‘quv jarayonida 5-darajaga yetib keldingiz!',
    icon: '👑',
    category: 'learning',
    requirement: '5-darajaga yetish',
    xpReward: 250,
  },
];

// ==========================================
// COURSES
// ==========================================
export const SEED_COURSES: Course[] = [
  {
    id: 'course-intro',
    title: 'Dasturlashga Kirish',
    slug: 'dasturlashga-kirish',
    description: 'Dasturlash nima, kompyuter qanday fikrlaydi va dasturchi kabi fikrlash asoslarini 0 dan o‘rganing.',
    shortDescription: '0 dan boshlovchilar uchun: fikrlash, algoritmlar va ilk kod.',
    level: 'boshlangich',
    category: 'kirish',
    thumbnail: '/images/courses/intro.jpg',
    estimatedHours: 4,
    published: true,
    order: 1,
    technologies: ['Algoritm', 'Mantiq', 'Terminal', 'Console'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-html',
    title: 'HTML Asoslari',
    slug: 'html-asoslari',
    description: 'Internetdagi barcha veb-saytlarning skeleti bo‘lgan HTML tilini to‘liq o‘rganing va shaxsiy sahifangizni yarating.',
    shortDescription: 'Veb sahifalarning suyagi va teglari bilan ishlash.',
    level: 'boshlangich',
    category: 'frontend',
    thumbnail: '/images/courses/html.jpg',
    estimatedHours: 6,
    published: true,
    order: 2,
    technologies: ['HTML5', 'Semantic Tags', 'Forms', 'Media'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-css',
    title: 'CSS Asoslari',
    slug: 'css-asoslari',
    description: 'Sahifalarga rang, chiroyli shakl va zamonaviy ko‘rinish berish: Flexbox, Grid va responsive dizayn.',
    shortDescription: 'Saytlarni chiroyli, zamonaviy va har qanday ekranga mos qilish.',
    level: 'boshlangich',
    category: 'frontend',
    thumbnail: '/images/courses/css.jpg',
    estimatedHours: 8,
    published: true,
    order: 3,
    technologies: ['CSS3', 'Flexbox', 'Grid', 'Media Queries'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-js',
    title: 'JavaScript Asoslari',
    slug: 'javascript-asoslari',
    description: 'Saytlarga jon kiritish! O‘zgaruvchilar, funksiyalar, shartlar va tugmalarni bosganda ishlaydigan interaktivlik.',
    shortDescription: 'Vebning eng mashhur dasturlash tili: mantiq va harakat.',
    level: 'boshlangich',
    category: 'frontend',
    thumbnail: '/images/courses/js.jpg',
    estimatedHours: 10,
    published: true,
    order: 4,
    technologies: ['JavaScript ES6', 'DOM', 'Events', 'Functions'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-prompt',
    title: 'Prompt Engineering Asoslari',
    slug: 'prompt-engineering',
    description: 'Sun’iy intellekt (ChatGPT, Claude, Gemini) bilan professional darajada muloqot qilish, RTCO modeli, Few-Shot, CoT va dasturlashda AI unumdorligini 10 barobarga oshirish sirlari.',
    shortDescription: 'Sun’iy intellektga mukammal so‘rov (prompt) yozish san’ati.',
    level: 'boshlangich',
    category: 'ai',
    thumbnail: '/images/courses/prompt.jpg',
    estimatedHours: 8,
    published: true,
    order: 5,
    technologies: ['Prompt Engineering', 'LLM', 'RTCO Modeli', 'Few-Shot', 'Chain-of-Thought'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-terminal',
    title: 'Linux Terminal & CLI Asoslari',
    slug: 'terminal-asoslari',
    description: 'Dasturchining asosiy quroli: fayl tizimi navigatsiyasi, bash buyruqlari (ls, cd, mkdir, rm, cat, grep), ruxsatlar va skriptlar.',
    shortDescription: 'Fayl tizimi, buyruqlar satri va terminalda ishlash san’ati.',
    level: 'boshlangich',
    category: 'backend',
    thumbnail: '/images/courses/terminal.jpg',
    estimatedHours: 4,
    published: true,
    order: 6,
    technologies: ['Linux', 'Bash', 'CLI', 'Terminal', 'Filesystem'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-git',
    title: 'Git va GitHub: Versiyalar Nazorati',
    slug: 'git-va-github',
    description: 'Kod tarixingizni boshqaring: git init, add, commit, branch, merge, pull request va GitHub orqali jamoaviy dasturlash.',
    shortDescription: 'Kodni xavfsiz saqlash, shoxlanish va jamoaviy ishlash.',
    level: 'boshlangich',
    category: 'kirish',
    thumbnail: '/images/courses/git.jpg',
    estimatedHours: 5,
    published: true,
    order: 7,
    technologies: ['Git', 'GitHub', 'Version Control', 'Branching', 'Commits'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-backend',
    title: 'Backend & Serverlar Asoslari',
    slug: 'backend-asoslari',
    description: 'Server qanday ishlaydi, Client-Server muloqoti, HTTP protokoli (GET, POST, PUT, DELETE), Node.js va Express yordamida REST API qurish.',
    shortDescription: 'Serverlar, HTTP protokoli va Node.js da REST API yaratish.',
    level: 'orta',
    category: 'backend',
    thumbnail: '/images/courses/backend.jpg',
    estimatedHours: 8,
    published: true,
    order: 8,
    technologies: ['Node.js', 'Express', 'HTTP', 'REST API', 'JSON'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-database',
    title: 'Ma’lumotlar Bazasi & SQL',
    slug: 'malumotlar-bazasi-sql',
    description: 'Relyatsion ma’lumotlar bazalari, SQL so‘rovlari (SELECT, WHERE, INSERT, UPDATE, DELETE), jadvallar va Primary Key arxitekturasi.',
    shortDescription: 'Relyatsion jadvallar, SQL so‘rovlari va ma’lumotlarni saqlash.',
    level: 'orta',
    category: 'database',
    thumbnail: '/images/courses/database.jpg',
    estimatedHours: 6,
    published: true,
    order: 9,
    technologies: ['SQL', 'Database', 'SQLite', 'Tables', 'Queries'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-react',
    title: 'React Asoslari: Zamonaviy UI',
    slug: 'react-asoslari',
    description: 'Interaktiv veb ilovalar: komponentlar, JSX, Props, useState va useEffect yordamida foydalanuvchi interfeysini boshqarish.',
    shortDescription: 'Komponentlar, hooks va zamonaviy SPA veb ilovalar.',
    level: 'orta',
    category: 'frontend',
    thumbnail: '/images/courses/react.jpg',
    estimatedHours: 10,
    published: true,
    order: 10,
    technologies: ['React', 'JSX', 'Hooks', 'Components', 'Virtual DOM'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'course-security',
    title: 'Kiberxavfsizlik va Web Himoya',
    slug: 'kiberxavfsizlik-asoslari',
    description: 'Veb xavfsizlik poydevori: XSS, SQL Injection xurujlaridan himoyalanish, parollarni xesh qilish (bcrypt), JWT va xavfsiz autentifikatsiya.',
    shortDescription: 'XSS, SQL Injection, xavfsiz parollar va veb himoya.',
    level: 'orta',
    category: 'security',
    thumbnail: '/images/courses/security.jpg',
    estimatedHours: 6,
    published: true,
    order: 11,
    technologies: ['Cybersecurity', 'Web Security', 'XSS', 'SQL Injection', 'Hashing'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_MODULES: Module[] = [
  // Intro modules
  {
    id: 'mod-intro-1',
    courseId: 'course-intro',
    title: '1-Modul: Dasturlash Falsafasi va Algoritm',
    description: 'Dasturchi kabi fikrlashni o‘rganamiz.',
    order: 1,
  },
  // HTML modules
  {
    id: 'mod-html-1',
    courseId: 'course-html',
    title: '1-Modul: Vebning Skeleti (HTML)',
    description: 'Teglar, matnlar va sahifa tuzilishi.',
    order: 1,
  },
  // CSS modules
  {
    id: 'mod-css-1',
    courseId: 'course-css',
    title: '1-Modul: Ranglar, Qutilar va Tartib',
    description: 'CSS selektorlari, Box model va tartiblash.',
    order: 1,
  },
  // JS modules
  {
    id: 'mod-js-1',
    courseId: 'course-js',
    title: '1-Modul: Jonli Veb (JavaScript)',
    description: 'O‘zgaruvchilar, funksiyalar va DOM boshqaruvi.',
    order: 1,
  },
  // Prompt Engineering modules
  {
    id: 'mod-prompt-1',
    courseId: 'course-prompt',
    title: '1-Modul: Sun’iy Intellekt va Prompt Falsafasi',
    description: 'LLM qanday fikrlaydi va RTCO oltin modeli.',
    order: 1,
  },
  {
    id: 'mod-prompt-2',
    courseId: 'course-prompt',
    title: '2-Modul: Ilg‘or Prompt Strategiyalari',
    description: 'Few-Shot va Chain-of-Thought usullari.',
    order: 2,
  },
  {
    id: 'mod-prompt-3',
    courseId: 'course-prompt',
    title: '3-Modul: Dasturlashda AI va Gallyutsinatsiya Nazorati',
    description: 'Kod yozdirish, cheklovlar va xavfsiz promptlar.',
    order: 3,
  },
  // Terminal modules
  {
    id: 'mod-terminal-1',
    courseId: 'course-terminal',
    title: '1-Modul: Linux Terminal va Fayl Tizimi',
    description: 'Buyruqlar satri, navigatsiya va fayllar bilan ishlash.',
    order: 1,
  },
  // Git modules
  {
    id: 'mod-git-1',
    courseId: 'course-git',
    title: '1-Modul: Git Asoslari va Shoxlanish',
    description: 'Versiyalar nazorati, commitlar va GitHub bilan ishlash.',
    order: 1,
  },
  // Backend modules
  {
    id: 'mod-backend-1',
    courseId: 'course-backend',
    title: '1-Modul: Serverlar va REST API',
    description: 'Client-Server modeli, HTTP so‘rovlar va Express router.',
    order: 1,
  },
  // Database modules
  {
    id: 'mod-database-1',
    courseId: 'course-database',
    title: '1-Modul: Relyatsion Bazalar va SQL',
    description: 'Jadvallar tuzilishi, SELECT va ma’lumotlarni boshqarish.',
    order: 1,
  },
  // React modules
  {
    id: 'mod-react-1',
    courseId: 'course-react',
    title: '1-Modul: React Komponentlari va State',
    description: 'JSX, Props, useState va dinamik UI yaratish.',
    order: 1,
  },
  // Security modules
  {
    id: 'mod-security-1',
    courseId: 'course-security',
    title: '1-Modul: Veb Xavfsizlik va Xurujlardan Himoya',
    description: 'XSS, SQL Injection va parollarni xavfsiz saqlash.',
    order: 1,
  },
];
